"""
스크린별 WP(Waypoint) 이동 시퀀스 정의
녹화된 이동 경로를 operation 형식으로 저장
"""
from matplotlib.style.core import context

# S1 WP3 시퀀스 (ARENA)
S1_WP3_ARENA = [
    # 2. 지도 뷰 정렬 (Ctrl + 드래그)
    {'operation': 'key_press_raw', 'key': 'ctrl', 'event': 'press', 'context': 'ARENA'},

    # [수정] 좌표 대신 screen_info의 Key 사용 (또는 숫자로 유지 가능)
    # monitor.py를 수정하지 않으셨다면 아래 숫자 좌표 그대로 사용:
    {'operation': 'mouse_drag', 'button': 'left', 'from_x': 438, 'from_y': 175, 'to_x': 700, 'to_y': 175,
     'duration': 0.5, 'delay_after': 0.2, 'context': 'ARENA'},

    {'operation': 'key_press_raw', 'key': 'ctrl', 'event': 'release', 'delay_after': 0.5, 'context': 'ARENA'},

    # 3. 목적지(점프대) 클릭 - ★ 여기가 핵심 수정 사항 ★
    # x, y 대신 key를 사용하여 screen_info.py의 좌표를 불러옵니다.
    {'operation': 'click_relative', 'key': 'wp3_jump_point_1', 'delay_after': 0.8, 'context': 'ARENA'},
    {'operation': 'click_relative', 'key': 'wp3_jump_point_2', 'delay_after': 0.5, 'context': 'ARENA'},

    # 4. 이동 대기
    {'operation': 'key_press', 'key': 'm', 'delay_after': 0.5, 'context': 'ARENA'},
    {'operation': 'wait_duration', 'duration': 10.0, 'context': 'ARENA'},
    # =========================================================================
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 0.304, 'context': 'ARENA', 'duration': 0.16},
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 0.24, 'context': 'ARENA', 'duration': 0.128},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.104, 'context': 'ARENA', 'duration': 0.12},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.113, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.264, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.648, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.6, 'context': 'ARENA', 'duration': 0.128},
    {'operation': 'key_press', 'key': 'a', 'delay_after': 0.735, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.329, 'context': 'ARENA', 'duration': 0.152},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.192, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.8, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.896, 'context': 'ARENA', 'duration': 0.152},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.168, 'context': 'ARENA', 'duration': 0.128},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.217, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.103, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.312, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 0.624, 'context': 'ARENA', 'duration': 0.272},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 0.48, 'context': 'ARENA', 'duration': 0.168},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 0.944, 'context': 'ARENA', 'duration': 0.152},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.176, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.408, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 1.393, 'context': 'ARENA', 'duration': 0.184},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.192, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.135, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.144, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.528, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 1.753, 'context': 'ARENA', 'duration': 0.2},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.352, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.176, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.168, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.144, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 2.351, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.152, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.329, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'f', 'delay_after': 0.208, 'context': 'ARENA', 'duration': 0.12},
    {'operation': 'key_press', 'key': 'q', 'delay_after': 0, 'context': 'ARENA'},

    # 여기에 변환된 S1 시퀀스 붙여넣기
]

# S2 WP3 시퀀스 (ARENA)
S2_WP3_ARENA = [

    # 2. 지도 뷰 정렬 (Ctrl + 드래그)
    {'operation': 'key_press_raw', 'key': 'ctrl', 'event': 'press', 'context': 'ARENA'},

    # [수정] 좌표 대신 screen_info의 Key 사용 (또는 숫자로 유지 가능)
    # monitor.py를 수정하지 않으셨다면 아래 숫자 좌표 그대로 사용:
    {'operation': 'mouse_drag', 'button': 'left', 'from_x': 490, 'from_y': 195, 'to_x': 730, 'to_y': 195,
     'duration': 0.5, 'delay_after': 0.2, 'context': 'ARENA'},

    {'operation': 'key_press_raw', 'key': 'ctrl', 'event': 'release', 'delay_after': 0.5, 'context': 'ARENA'},

    # 3. 목적지(점프대) 클릭 - ★ 여기가 핵심 수정 사항 ★
    # x, y 대신 key를 사용하여 screen_info.py의 좌표를 불러옵니다.
    {'operation': 'click_relative', 'key': 'map_marker_reference', 'delay_after': 0.8},
    {'operation': 'click_relative', 'key': 'wp3_jump_point_1', 'delay_after': 0.8, 'context': 'ARENA'},
    {'operation': 'click_relative', 'key': 'wp3_jump_point_2', 'delay_after': 0.5, 'context': 'ARENA'},

    # 4. 이동 대기
    {'operation': 'key_press', 'key': 'm', 'delay_after': 0.5, 'context': 'ARENA'},
    {'operation': 'wait_duration', 'duration': 10.0, 'context': 'ARENA'},
    {'operation': 'key_press', 'key': 'space', 'delay_after': 0.224, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 0.112, 'context': 'ARENA', 'duration': 0.104},
    {'operation': 'key_press', 'key': 'shift', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.24, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.665, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 1.12, 'context': 'ARENA', 'duration': 0.112},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.088, 'context': 'ARENA', 'duration': 0.12},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.168, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.089, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.647, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 1.081, 'context': 'ARENA', 'duration': 0.128},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.752, 'context': 'ARENA', 'duration': 0.128},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.2, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.544, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.897, 'context': 'ARENA', 'duration': 0.119},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.144, 'context': 'ARENA', 'duration': 0.136},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.168, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.544, 'context': 'ARENA'},
    {'operation': 'key_press', 'key': 'shift', 'delay_after': 1.216, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.096, 'context': 'ARENA', 'duration': 0.137},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.176, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.095, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.192, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.496, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.768, 'context': 'ARENA', 'duration': 0.136},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.128, 'context': 'ARENA', 'duration': 0.152},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.208, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 2.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.175, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.144, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.176, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 2.297, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 1.456, 'context': 'ARENA', 'duration': 0.24},
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 0.808, 'context': 'ARENA', 'duration': 0.127},
    {'operation': 'key_press', 'key': 'f', 'delay_after': 0.432, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'q', 'delay_after': 0, 'context': 'ARENA', 'duration': 0.137},

]

# S3 WP3 시퀀스 (ARENA)
S3_WP3_ARENA = [
    # 2. 지도 뷰 정렬 (Ctrl + 드래그)
    {'operation': 'key_press_raw', 'key': 'ctrl', 'event': 'press', 'context': 'ARENA'},

    # [수정] 좌표 대신 screen_info의 Key 사용 (또는 숫자로 유지 가능)
    # monitor.py를 수정하지 않으셨다면 아래 숫자 좌표 그대로 사용:
    {'operation': 'mouse_drag', 'button': 'left', 'from_x': 438, 'from_y': 175, 'to_x': 700, 'to_y': 175,
     'duration': 0.5, 'delay_after': 0.2, 'context': 'ARENA'},

    {'operation': 'key_press_raw', 'key': 'ctrl', 'event': 'release', 'delay_after': 0.5, 'context': 'ARENA'},

    # 3. 목적지(점프대) 클릭 - ★ 여기가 핵심 수정 사항 ★
    # x, y 대신 key를 사용하여 screen_info.py의 좌표를 불러옵니다.
    {'operation': 'click_relative', 'key': 'map_marker_reference', 'delay_after': 0.8},
    {'operation': 'click_relative', 'key': 'wp3_jump_point_1', 'delay_after': 0.8, 'context': 'ARENA'},
    {'operation': 'click_relative', 'key': 'wp3_jump_point_2', 'delay_after': 0.5, 'context': 'ARENA'},
    # 4. 이동 대기
    {'operation': 'key_press', 'key': 'm', 'delay_after': 0.5, 'context': 'ARENA'},
    {'operation': 'wait_duration', 'duration': 10.0, 'context': 'ARENA'},
    {'operation': 'key_press', 'key': 'space', 'delay_after': 0.216, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 0.104, 'context': 'ARENA', 'duration': 0.12},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.08, 'context': 'ARENA', 'duration': 0.104},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.456, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.689, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 1.295, 'context': 'ARENA', 'duration': 0.128},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.112, 'context': 'ARENA', 'duration': 0.128},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.192, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 2.057, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.304, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.48, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 1.847, 'context': 'ARENA', 'duration': 0.136},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.081, 'context': 'ARENA', 'duration': 0.144},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.184, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.704, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 1.392, 'context': 'ARENA', 'duration': 0.128},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.08, 'context': 'ARENA', 'duration': 0.152},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.199, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.777, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 1.088, 'context': 'ARENA', 'duration': 0.112},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.224, 'context': 'ARENA', 'duration': 0.136},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.184, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.144, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.392, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 1.712, 'context': 'ARENA', 'duration': 0.168},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.344, 'context': 'ARENA', 'duration': 0.144},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.296, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.832, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 1.553, 'context': 'ARENA', 'duration': 0.272},
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 0.096, 'context': 'ARENA', 'duration': 0.143},
    {'operation': 'key_press', 'key': 'space', 'delay_after': 0.144, 'context': 'ARENA'},
    {'operation': 'key_press', 'key': 'space', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press', 'key': 'space', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 1.856, 'context': 'ARENA', 'duration': 0.104},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.168, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.097, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.96, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'f', 'delay_after': 0.152, 'context': 'ARENA', 'duration': 0.103},
    {'operation': 'key_hold', 'key': 'q', 'delay_after': 0, 'context': 'ARENA', 'duration': 0.128},
]

# S4 WP3 시퀀스 (ARENA)
S4_WP3_ARENA = [
    # 2. 지도 뷰 정렬 (Ctrl + 드래그)
    {'operation': 'key_press_raw', 'key': 'ctrl', 'event': 'press', 'context': 'ARENA'},

    # [수정] 좌표 대신 screen_info의 Key 사용 (또는 숫자로 유지 가능)
    # monitor.py를 수정하지 않으셨다면 아래 숫자 좌표 그대로 사용:
    {'operation': 'mouse_drag', 'button': 'left', 'from_x': 438, 'from_y': 175, 'to_x': 700, 'to_y': 175,
     'duration': 0.5, 'delay_after': 0.2, 'context': 'ARENA'},

    {'operation': 'key_press_raw', 'key': 'ctrl', 'event': 'release', 'delay_after': 0.5, 'context': 'ARENA'},

    # 3. 목적지(점프대) 클릭 - ★ 여기가 핵심 수정 사항 ★
    # x, y 대신 key를 사용하여 screen_info.py의 좌표를 불러옵니다.
    {'operation': 'click_relative', 'key': 'map_marker_reference', 'delay_after': 0.8},
    {'operation': 'click_relative', 'key': 'wp3_jump_point_1', 'delay_after': 0.8, 'context': 'ARENA'},
    {'operation': 'click_relative', 'key': 'wp3_jump_point_2', 'delay_after': 0.5, 'context': 'ARENA'},
    # 4. 이동 대기
    {'operation': 'key_press', 'key': 'm', 'delay_after': 0.5, 'context': 'ARENA'},
    {'operation': 'wait_duration', 'duration': 10.0, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 0.232, 'context': 'ARENA', 'duration': 0.135},
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 0.128, 'context': 'ARENA', 'duration': 0.12},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.08, 'context': 'ARENA', 'duration': 0.12},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.449, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.096, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.936, 'context': 'ARENA', 'duration': 0.16},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.08, 'context': 'ARENA', 'duration': 0.12},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.799, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.745, 'context': 'ARENA', 'duration': 0.12},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.104, 'context': 'ARENA', 'duration': 0.112},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.176, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.232, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.784, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.672, 'context': 'ARENA', 'duration': 0.136},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.112, 'context': 'ARENA', 'duration': 0.128},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.184, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.121, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.087, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.647, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.288, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.144, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.152, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.088, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.16, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.496, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.289, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.144, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.176, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.383, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.36, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.168, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.121, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.144, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.152, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.208, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.152, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.152, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.127, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.272, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.473, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 1.216, 'context': 'ARENA', 'duration': 0.152},
    {'operation': 'key_press', 'key': 's', 'delay_after': 0.944, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.08, 'context': 'ARENA', 'duration': 0.104},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.184, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.105, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 0.568, 'context': 'ARENA', 'duration': 0.831},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.192, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.136, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.272, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 0.983, 'context': 'ARENA', 'duration': 0.745},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 0.832, 'context': 'ARENA', 'duration': 0.12},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.144, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 2.513, 'context': 'ARENA'},
    {'operation': 'key_press', 'key': 'f', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'q', 'delay_after': 0, 'context': 'ARENA', 'duration': 0.128},


]

# S5 WP3 시퀀스 (ARENA)
S5_WP3_ARENA = [
    # 1. 지도 뷰 정렬 (마우스 휠 스크롤 UP)
    # amount: 양수(+)는 UP(줌인), 음수(-)는 DOWN(줌아웃)
    # x, y 좌표를 지정하지 않으면 화면 중앙에서 스크롤하도록 로직을 짤 것입니다.
    {'operation': 'mouse_scroll', 'amount': 1500, 'delay_after': 0.2, 'context': 'ARENA'},
    {'operation': 'mouse_scroll', 'amount': 1500, 'delay_after': 0.2, 'context': 'ARENA'},
    {'operation': 'mouse_scroll', 'amount': 1500, 'delay_after': 0.2, 'context': 'ARENA'},
    {'operation': 'mouse_scroll', 'amount': 1500, 'delay_after': 1.0, 'context': 'ARENA'},  # 마지막엔 충분한 대기

    # 2. 목적지(점프대) 클릭 (S1~S4와 동일하게 사용)
    {'operation': 'click_relative', 'key': 'wp3_jump_point_1', 'delay_after': 0.8, 'context': 'ARENA'},
    {'operation': 'click_relative', 'key': 'wp3_jump_point_2', 'delay_after': 0.5, 'context': 'ARENA'},
    # 3. 이동대기
    {'operation': 'key_press', 'key': 'm', 'delay_after': 0.5, 'context': 'ARENA'},
    {'operation': 'wait_duration', 'duration': 10.0, 'context': 'ARENA'},
    # ========================================================================
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 0.272, 'context': 'ARENA', 'duration': 0.103},
    {'operation': 'key_hold', 'key': 'space', 'delay_after': 0.168, 'context': 'ARENA', 'duration': 0.104},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.08, 'context': 'ARENA', 'duration': 0.112},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.129, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.216, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.024, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.696, 'context': 'ARENA', 'duration': 0.152},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.088, 'context': 'ARENA', 'duration': 0.127},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.129, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.104, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.536, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.168, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.592, 'context': 'ARENA', 'duration': 0.112},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.336, 'context': 'ARENA', 'duration': 0.152},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.176, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.08, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.128, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.673, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.424, 'context': 'ARENA', 'duration': 0.152},
    {'operation': 'key_hold', 'key': 'shift', 'delay_after': 0.528, 'context': 'ARENA', 'duration': 0.168},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.184, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.096, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.112, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.145, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.103, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 0.937, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 1.112, 'context': 'ARENA', 'duration': 0.807},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.216, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.129, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.383, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 2.361, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'press', 'delay_after': 0.191, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'press', 'delay_after': 0.12, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 'space', 'event': 'release', 'delay_after': 0.304, 'context': 'ARENA'},
    {'operation': 'key_press_raw', 'key': 's', 'event': 'release', 'delay_after': 1.761, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'a', 'delay_after': 1.376, 'context': 'ARENA', 'duration': 0.2},
    {'operation': 'key_press', 'key': 'f', 'delay_after': 0.264, 'context': 'ARENA'},
    {'operation': 'key_hold', 'key': 'q', 'delay_after': 0, 'context': 'ARENA', 'duration': 0.112},
    # 여기에 변환된 S5 시퀀스 붙여넣기
]


def get_wp_sequence(screen_id: str, wp_name: str = 'wp3', context: str = 'ARENA'):
    """
    스크린별 WP 시퀀스 반환

    Args:
        screen_id: 화면 ID (S1~S5)
        wp_name: 웨이포인트 이름 (현재는 wp3만 사용)
        context: 컨텍스트 (ARENA 또는 FIELD)

    Returns:
        list: operation 리스트, 없으면 빈 리스트
    """
    key = f"{screen_id.upper()}_WP3_{context.upper()}"

    sequences = {
        'S1_WP3_ARENA': S1_WP3_ARENA,
        'S2_WP3_ARENA': S2_WP3_ARENA,
        'S3_WP3_ARENA': S3_WP3_ARENA,
        'S4_WP3_ARENA': S4_WP3_ARENA,
        'S5_WP3_ARENA': S5_WP3_ARENA,
    }

    sequence = sequences.get(key, [])

    if not sequence:
        print(f"WARN: WP sequence not found for key '{key}'")

    return sequence