wp4_glider_sequence:
  - phase: "jump_start"
    actions:
      # 점프 2회
      - { type: "key_press", key: "space", duration: 0.3 }
      - { type: "key_press", key: "space", duration: 0.3 }

      # 글라이더 탑승 (즉시)
      - { type: "key_press", key: "shift", duration: 0.2 }  # duration 0으로!

      # 바로 S+Space 상승 (wait 없이!)
      - { type: "key_hold", key: "s", duration: 0.2 }      # S키 즉시 누름
      - { type: "key_press", key: "space", duration: 0.3 } # Space 바로 입력
      - { type: "key_release", key: "s", duration: 0.3 }   # S키 해제
      - {type: "key_press", key: "shift", duration: 2.0}

  - phase: "maintain_flight"
    repeat: 5
    interval: 2.0  # 1.8 → 2.0
    actions:
      - { type: "key_press", key: "shift", duration: 0.6 }     # 0.5 → 0.6
      - { type: "key_hold", key: "s", duration: 0.3 }         # 0.2 → 0.3
      - { type: "key_press", key: "space", duration: 0.4 }    # 0.3 → 0.4
      - { type: "key_release", key: "s", duration: 0.5 }      # 0.6 → 0.7
      - { type: "key_press", key: "shift", duration: 0.2 }    # 0.1 → 0.2

  - phase: "landing"
    description: "목적지 도착 후 착륙"
    actions:
      # 착륙 준비 (잠시 대기)
      - { type: "wait", duration: 1.0 }
      # 착륙 (스페이스)
      - { type: "key_press", key: "Q", duration: 0.3 }
      # 안정화 대기
      - { type: "wait", duration: 0.5 }